
name: Package Application with Pyinstaller

on:
    push:
        branches: [ main ]
jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
  
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
  
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller converteraudiofile.py
      # Optionally verify that it works (provided that it does not need user interaction)
      - run: ./dist/your-code/converteraudiofile
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*