# This is a basic workflow to help you get started with Actions

name: Build Package Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deb:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build deb
        shell: bash
        run: |
          sudo apt install -y ffmpeg
          pip3 install -r requirements.txt pyinstaller
          pyinstaller converterAudio.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: converterAudio.deb  # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: target/converterAudio.deb
          # The desired behavior if no files are found using the provided path.

  build_dmg:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build dmg
        shell: bash
        run: |
          sudo pip3 install -r requirements.txt pyinstaller
          pyinstaller converterAudio.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: converterAudio.dmg  # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: target/converterAudio.dmg
          # The desired behavior if no files are found using the provided path.

  build_exe:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.x"
        
      - uses: AnimMouse/setup-ffmpeg@v1
        id: setup-ffmpeg

      # Runs a set of commands using the runners shell
      - name: Build exe
        shell: powershell
        run: |
          pip3 install pip -U
          pip3 install -r requirements.txt pyinstaller
          pyinstaller converterAudio.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: converterAudio.exe  # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: .\target\converterAudio.exe
          # The desired behavior if no files are found using the provided path.

  publish:
    runs-on: ubuntu-latest
    needs: [ build_deb, build_dmg, build_exe ]
    steps:
      - name: Download deb
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: converterAudio.deb  # optional
          path: /tmp

      - name: Download dmg
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: converterAudio.dmg  # optional
          path: /tmp

      - name: Download exe
        uses: actions/download-artifact@v3.0.1
        with:
          # Artifact name
          name: converterAudio.exe  # optional
          path: /tmp

      - name: Delete Artifact
        # You may pin to the exact commit or the version.
        # uses: GeekyEggo/delete-artifact@b73cb986740e466292a536d0e32e2666c56fdeb3
        uses: GeekyEggo/delete-artifact@v2.0.0
        with:
          name: |
            converterAudio.deb
            converterAudio.dmg
            converterAudio.exe

      - name: Generate Prerelease Release Notes
        run: |
          zip /tmp/converterAudio_for_Windows.exe.zip /tmp/converterAudio.exe && rm /tmp/converterAudio.exe || ls /tmp
          mv /tmp/converterAudio.dmg /tmp/converterAudio_for_macOS.dmg
          mv /tmp/converterAudio.deb /tmp/converterAudio_for_Ubuntu.deb
          echo '### converterAudio`latest`' >> ReleaseNotes.md
          echo '> Written by @sabasacustico with love.' >> ReleaseNotes.md
          echo '> Generated by Github Actions.' >> ReleaseNotes.md

      - name: Delete Old Prerelease
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: "v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1.11.2
        with:
          bodyFile: ReleaseNotes.md
          artifacts: "/tmp/converterAudio*.*"
          tag: "v1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}